plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE
theme: jekyll-theme-minimal
title: [PulseHPT User Manual]
description: [User Manual for PulseHPT 3-in-1 Shutter Speed Tester]