plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE
remote_theme: pages-themes/primer@v0.6.0
title: PulseHPT Shutter Speed Tester
description: 3-in-1 Portable Shutter Speed Tester
permissions:
  id-token: write
  pages: write
  contents: read
markdown: kramdown
